# Generated by Django 3.2.6 on 2021-08-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
