# Generated by Django 3.2.6 on 2021-08-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_artist_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='nationality',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
